const clinicColumns = [
  { key: "id", name: "ID", resizable: true },
  { key: "name", name: "Name", resizable: true, sortable: true },
  { key: "open", name: "Open Time", resizable: true, sortable: true },
  { key: "close", name: "Close Time", resizable: true, sortable: true },
  {
    key: "officeAddress",
    name: "Office Address",
    resizable: true,
    sortable: true,
  },
];

const clinicRows = [
  {
    id: 25,
    name: "Jon",
    open: "09:00 AM",
    close: "05:00 PM",
    officeAddress: "27 Houston California",
  },
  {
    id: 885,
    name: "Cersei",
    open: "09:00 AM",
    close: "05:00 PM",
    officeAddress: "27 Houston California",
  },
  {
    id: 78,
    name: "Jaime",
    open: "09:00 AM",
    close: "05:00 PM",
    officeAddress: "27 Houston California",
  },
  {
    id: 23,
    name: "Arya",
    open: "09:00 AM",
    close: "05:00 PM",
    officeAddress: "27 Houston California",
  },
  {
    id: 55,
    name: "Daenerys",
    open: "09:00 AM",
    close: "05:00 PM",
    officeAddress: "27 Houston California",
  },
  {
    id: 66,
    name: "Hommie",
    open: "09:00 AM",
    close: "05:00 PM",
    officeAddress: "27 Houston California",
  },
  {
    id: 77,
    name: "Ferrara",
    open: "09:00 AM",
    close: "05:00 PM",
    officeAddress: "27 Houston California",
  },
  {
    id: 88,
    name: "Rossini",
    open: "09:00 AM",
    close: "05:00 PM",
    officeAddress: "27 Houston California",
  },
  {
    id: 44,
    name: "Harvey",
    open: "09:00 AM",
    close: "05:00 PM",
    officeAddress: "27 Houston California",
  },
  {
    id: 78,
    name: "Harvey",
    open: "09:00 AM",
    close: "05:00 PM",
    officeAddress: "27 Houston California",
  },
  {
    id: 79,
    name: "Harvey",
    open: "09:00 AM",
    close: "05:00 PM",
    officeAddress: "27 Houston California",
  },
  {
    id: 29,
    name: "Harvey",
    open: "09:00 AM",
    close: "05:00 PM",
    officeAddress: "27 Houston California",
  },
];
const doctorColumns = [
  { key: "id", name: "ID", resizable: true },
  { key: "firstName", name: "First Name", resizable: true, sortable: true },
  { key: "lastName", name: "Last Name", resizable: true, sortable: true },
  { key: "address", name: "Address", resizable: true, sortable: true },
];

const doctorRows = [
  { id: 44, firstName: "Jon", lastName: "Twain", address: "Sopore, Sagipora" },
  {
    id: 990,
    firstName: "Cersei",
    lastName: "Twain",
    address: "Sopore, Sagipora",
  },
  {
    id: 224,
    firstName: "Jaime",
    lastName: "Twain",
    address: "Sopore, Sagipora",
  },
  {
    id: 334,
    firstName: "Arya",
    lastName: "Twain",
    address: "Sopore, Sagipora",
  },
  {
    id: 440,
    firstName: "Daenerys",
    lastName: "Twain",
    address: "Sopore, Sagipora",
  },
  {
    id: 370,
    firstName: "Hommie",
    lastName: "Twain",
    address: "Sopore, Sagipora",
  },
  {
    id: 284,
    firstName: "Ferrara",
    lastName: "Twain",
    address: "Sopore, Sagipora",
  },
  {
    id: 775,
    firstName: "Rossini",
    lastName: "Twain",
    address: "Sopore, Sagipora",
  },
  {
    id: 980,
    firstName: "Harvey",
    lastName: "Twain",
    address: "Sopore, Sagipora",
  },
  {
    id: 354,
    firstName: "Harvey",
    lastName: "Twain",
    address: "Sopore, Sagipora",
  },
  {
    id: 79,
    firstName: "Harvey",
    lastName: "Twain",
    address: "Sopore, Sagipora",
  },
  {
    id: 29,
    firstName: "Harvey",
    lastName: "Twain",
    address: "Sopore, Sagipora",
  },
];
const userColumns = [
  { key: "id", name: "ID", resizable: true },
  { key: "firstName", name: "First Name", resizable: true, sortable: true },
  { key: "lastName", name: "Last Name", resizable: true, sortable: true },
  { key: "address", name: "Address", resizable: true, sortable: true },
  {
    key: "appointmentDate",
    name: "Appointment Date",
    resizable: true,
    sortable: true,
  },
  { key: "doctor", name: "Doctor", resizable: true, sortable: true },
  { key: "clinic", name: "Clinic", resizable: true, sortable: true },
];

const userRows = [
  {
    id: 154,
    firstName: "ALbert",
    lastName: "Helski",
    address: "Sopore, Sagipora",
    appointmentDate: "23-June-2023",
    doctor: "Alaxnder",
    clinic: "Summer Hall",
  },
  {
    id: 990,
    firstName: "Cersei",
    lastName: "Twain",
    address: "Sopore, Sagipora",
    appointmentDate: "31-July-2020",
    doctor: "Nadeem",
    clinic: "Tripmax",
  },
  {
    id: 224,
    firstName: "Jaime",
    lastName: "Twain",
    address: "Sopore, Sagipora",
    appointmentDate: "31-July-2020",
    doctor: "Nadeem",
    clinic: "Tripmax",
  },
  {
    id: 334,
    firstName: "Arya",
    lastName: "Twain",
    address: "Sopore, Sagipora",
    appointmentDate: "31-July-2020",
    doctor: "Nadeem",
    clinic: "Tripmax",
  },
  {
    id: 440,
    firstName: "Daenerys",
    lastName: "Twain",
    address: "Sopore, Sagipora",
    appointmentDate: "31-July-2020",
    doctor: "Nadeem",
    clinic: "Tripmax",
  },
  {
    id: 370,
    firstName: "Hommie",
    lastName: "Twain",
    address: "Sopore, Sagipora",
    appointmentDate: "31-July-2020",
    doctor: "Nadeem",
    clinic: "Tripmax",
  },
  {
    id: 284,
    firstName: "Ferrara",
    lastName: "Twain",
    address: "Sopore, Sagipora",
    appointmentDate: "31-July-2020",
    doctor: "Nadeem",
    clinic: "Tripmax",
  },
  {
    id: 775,
    firstName: "Rossini",
    lastName: "Twain",
    address: "Sopore, Sagipora",
    appointmentDate: "31-July-2020",
    doctor: "Nadeem",
    clinic: "Tripmax",
  },
  {
    id: 980,
    firstName: "Harvey",
    lastName: "Twain",
    address: "Sopore, Sagipora",
    appointmentDate: "31-July-2020",
    doctor: "Nadeem",
    clinic: "Tripmax",
  },
  {
    id: 354,
    firstName: "Harvey",
    lastName: "Twain",
    address: "Sopore, Sagipora",
    appointmentDate: "31-July-2020",
    doctor: "Nadeem",
    clinic: "Tripmax",
  },
  {
    id: 79,
    firstName: "Harvey",
    lastName: "Twain",
    address: "Sopore, Sagipora",
    appointmentDate: "31-July-2020",
    doctor: "Nadeem",
    clinic: "Tripmax",
  },
  {
    id: 29,
    firstName: "Harvey",
    lastName: "Twain",
    address: "Sopore, Sagipora",
    appointmentDate: "31-July-2020",
    doctor: "Nadeem",
    clinic: "Tripmax",
  },
];

const data = [
  {
    rows: clinicRows,
    columns: clinicColumns,
  },
  {
    rows: doctorRows,
    columns: doctorColumns,
  },
  {
    rows: userRows,
    columns: userColumns,
  },
];

export default data;
